videos:
  - https://www.youtube.com/watch?v=ia7Vp0Ti9ao
  - https://www.youtube.com/watch?v=75s-BZsZqf0
  - https://www.youtube.com/watch?v=w34tZie5Xvo
  - https://www.youtube.com/watch?v=puGoX9XQXMo


dl_path: /mnt/e/短视频/素材/youtube/dance_kids/
